version: '3.8'
services:
  server-dev:
    command: sleep infinity
    build:
      context: ..
      dockerfile: Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - ..:/usr/src/app
    env_file:
      - ../.env
    networks:
      - my_network

networks:
  my_network:
    external: true