version: '3.8'
services:
  server-prod:
    build:
      context: ..
      dockerfile: Dockerfile
      target: final
    ports:
      - 8080:8080
    env_file:
      - ../.env
    networks:
      - my_network

networks:
  my_network:
    external: true