version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DockMaster
    ports:
      - "5432:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "80:80"
    networks:
      - my_network

  docker-in-docker:
    image: docker:dind
    privileged: true
    ports:
      - 2375:2375
    command: ["--api-cors-header='*'", "-H", "tcp://0.0.0.0:2375"]
    environment:
      - DOCKER_TLS_CERTDIR= # Disable TLS by setting this to an empty value
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres-data:
