name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Define the build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Build
        run: cargo build --verbose

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install and run Checkmate
        run: cargo install checkmate && cargo checkmate

      - name: Run Tests
        run: cargo test
