name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Define the build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Build (debug)
        run: cargo build --verbose
        working-directory: dock_master

      - name: Build (release)
        run: cargo build --release --verbose
        working-directory: dock_master

      - name: Generate Documentation
        run: cargo doc --no-deps
        working-directory: dock_master

      - name: Upload Binary Artifact (release)
        uses: actions/upload-artifact@v4
        with:
          name: DockMasterApi
          path: dock_master/target/release/dock_master

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install and run Checkmate
        run: cargo install cargo-checkmate && cargo checkmate
        working-directory: dock_master

      - name: Run Tests
        run: cargo test
        working-directory: dock_master
